added ADB-PLUGIN
oracle-samples/adbs-tools pull request #13
Opened 2023-03-02 17:11 UTC by vinit-ramon

2023-03-03 08:22 UTC, spanchum approved these changes
looks good

2023-03-03 08:24 UTC, spanchum approved these changes

2023-03-06 05:31 UTC, SantoshKChaudhari requested changes

2023-03-06 05:31 UTC, SantoshKChaudhari commented on adb-grafana-plugin/README.md
> +It is a datasouce backend plugin which requires username, password and basic connection string to connect to Oracle ADB.
typo - datasource

2023-03-06 05:31 UTC, SantoshKChaudhari commented on adb-grafana-plugin/README.md
> +First Download the Plugin Zip file from https://bitbucket.oci.oraclecorp.com/users/vivinitk/repos/oracle-adb-grafana-plugin/browse and Extract it. Let's say the extracted path is $plug_path and it co
remove internal bit bucket link reference

2023-03-06 05:31 UTC, SantoshKChaudhari commented on adb-grafana-plugin/README.md
> +https://bitbucket.oci.oraclecorp.com/users/vivinitk/repos/oracle-oracleadb-datasource/browse/README.md?at=refs%2Fheads%2Fnewplug
remove the internal link reference and use the public link

2023-03-06 05:31 UTC, SantoshKChaudhari commented on adb-grafana-plugin/dist/README.md
> +First Download the Plugin Zip file from https://bitbucket.oci.oraclecorp.com/users/vivinitk/repos/oracle-adb-grafana-plugin/browse and Extract it. Let's say the extracted path is $plug_path and it co
remove internal reference

2023-03-06 05:31 UTC, SantoshKChaudhari commented on adb-grafana-plugin/src/README.md
> +First Download the Plugin Zip file from https://bitbucket.oci.oraclecorp.com/users/vivinitk/repos/oracle-adb-grafana-plugin/browse and Extract it. Let's say the extracted path is $plug_path and it co
remove internal link reference

2023-03-06 06:41 UTC, SantoshKChaudhari approved these changes

2023-03-06 06:46 UTC, merged